### ISSUE TITLE
Uncaught Error: Class "SpreadCompat" not found

### ISSUE THREAD

**Issue by jonanthonii** [lekoala/spread-compat#1]
Hi! I'm having trouble starting/using spread-compat, I already installed the package and added this line already
`use LeKoala\SpreadCompat;
use LeKoala\SpreadCompat\Xlsx\Simple;
use LeKoala\SpreadCompat\Xlsx\XlsxAdapter;

SpreadCompat::$preferredXlsxAdapter = SpreadCompat::SIMPLE; `

But I keep getting **Uncaught Error: Class "LeKoala\SpreadCompat" not found**

**Comment by lekoala** [comment]
use LeKoala\SpreadCompat\SpreadCompat;

this should do it :) you have the class and the namespace which are the same

**Comment by jonanthonii** [comment]
> use LeKoala\SpreadCompat\SpreadCompat;
> 
> this should do it :) you have the class and the namespace which are the same

i did that before too and this is the error that i encountered:
**Fatal error: Uncaught Error: Access to undeclared static property LeKoala\SpreadCompat\SpreadCompat::$preferredXlsxAdapter**

**Comment by lekoala** [comment]
I'm not sure what's your issue but the static variable is there and should be easily discoverable by your ide

https://github.com/lekoala/spread-compat/blob/68d32ee0bbe6e89a317d51553ccc0a6d8c96b6ff/src/SpreadCompat.php#L28

and here is an example of this being used

https://github.com/lekoala/silverstripe-excel-import-export/blob/2b3e21ddf6b0060b9b64949700d8a1d8c5231f57/_config.php#L3-L11

**Comment by lekoala** [comment]
closing this i think it should be fine
