### ISSUE TITLE
Error in the separator argument usage

### ISSUE THREAD

**Issue by nyamsprod** [lekoala/spread-compat#3]
https://github.com/lekoala/spread-compat/blob/3b28d3686f19dd74762f55f849d608bc703b150f/src/Csv/Native.php#L36

the `$this->eol` variable is not the delimiter/separator variable.

**Comment by lekoala** [comment]
yes i know, i'm using the method to split the file into lines
it would deserves a little comment that this is intended

**Comment by lekoala** [comment]
added a comment here
https://github.com/lekoala/spread-compat/commit/46f2ee895db91a6f41bbb1a0374a7d113ae5c525

**Comment by nyamsprod** [comment]
I might be wrong or late in the comment (both are not interely exclusive 😛 because I did not tested the assertion but your usage of eol as a separator might introduced some subtle bugs if your CSV document contains cell with multilined content 🤔

**Comment by lekoala** [comment]
:) that's entirely possible. I don't remember where i read that the str_getcsv (maybe here https://www.php.net/manual/fr/function.str-getcsv.php#101888) would take care of these but i may be wrong. if you have a test string with the issue let me know and I'll be happy to add it to the test suite

**Comment by nyamsprod** [comment]
here's a example

```php
<?php

$document = <<<CSV
Data 2-1,Data 2-2,"Data 2-3
is on multiple lines
you see"
CSV;

$data = str_getcsv($document, "\n"); //parse the rows
var_dump([...array_map(fn (string $row) => str_getcsv($row, ","), $data)]);
// returns
//  [
//  0 => array:3 [
//    0 => "Data 2-1"
//    1 => "Data 2-2"
//    2 => "Data 2-3"
//  ]
//  1 => array:1 [
//    0 => "is on multiple lines"
//  ]
//  2 => array:1 [
//    0 => "you see""
//  ]
//]

var_dump([...str_getcsv($document)]);
//returns
// array:3 [
//  0 => "Data 2-1"
//  1 => "Data 2-2"
//  2 => """
//    Data 2-3\n
//    is on multiple lines\n
//    you see
//    """
//]
```

That's one of the multiple reasons why I have avoided `str_getcsv` because the function behaviour is IMHO too buggy to be used I prefer creating a temporary file and use `fgetcsv`. That's more stable as an API ... my 2 cents ... still buggy but less that `str_getcsv` for a generic usage at least.

**Comment by lekoala** [comment]
oh that's great
it actually makes the code even simpler :-)
https://github.com/lekoala/spread-compat/commit/990a7c374a77f607467a90919864ea982bcc5c64
